global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'node_exporter'
    static_configs:
      - targets: ['node-exporter:9100']

  - job_name: 'stacks_signer_node'
    static_configs:
      - targets: ['69.2.42.123:9155']

  - job_name: 'stacks_node'
    static_configs:
      - targets: ['69.2.42.123:9153']
