global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'node_exporter'
    static_configs:
      - targets: ['node-exporter:9100']

  - job_name: 'stacks_signer_node'
    static_configs:
      - targets: ['x.x.x.x:9154']

  - job_name: 'stacks_node'
    static_configs:
      - targets: ['x.x.x.x:9153']
